CREATE TABLE IF NOT EXISTS FOOTBALLERS (
ID int,
NAME VARCHAR (2014),
shirtnumber int 
); 
INSERT INTO FOOTBALLERS ( ID, NAME, SHIRTNUMBER)
VALUES
( '4', 'NEYMAR jr', '10'),
( '5', 'C.RONALDO', '7');

SELECT * FROM FOOTBALLERS WHERE NAME='NEYMAR jr' OR SHIRTNUMBER='10';
SELECT * FROM FOOTBALLERS WHERE NAME LIKE '%A';